version: "3"
services:
  docs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    networks:
      - jenkins
    restart: always
networks:
  jenkins:
    external: true
